name: build

on:
  workflow_dispatch:
    inputs:
      use_cache:
        description: 'Use cache for host tools'
        required: true
        default: 'false'
        type: choice
        options:
        - true
        - false
      test_build:
        description: 'Test build (only spec target) '
        required: true
        default: 'false'
        type: choice
        options:
        - true
        - false
      target_name:
        description: 'Target Name for test build'
        required: false
        default: 'r3d'
        type: string
      package_dir:
        description: 'Package Dir for test build'
        required: false
        default: ''
        type: string
      fake_build:
        description: 'Fake build'
        required: true
        default: 'false'
        type: choice
        options:
        - true
        - false
      suffix:
        description: 'TAG suffix'
        required: false
        default: ''
        type: string

env:
  TEST_BUILD: ${{ github.event.inputs.test_build == 'true' }}
  FAKE_BUILD: ${{ github.event.inputs.fake_build == 'true' }}
  TAG_SUFFIX: ${{ github.event.inputs.fake_build == 'true' && '-fake' || github.event.inputs.test_build == 'true' && '-test' || '' }}
  TARGET_NAME: ${{ github.event.inputs.target_name }}
  PACKAGE_DIR: ${{ github.event.inputs.package_dir }}
  REPO_URL: https://github.com/openwrt-xiaomi/openwrt
  REPO_LNK: openwrt-xiaomi/openwrt
  REPO_BRANCH: xq-24.10
  TAG_PREFIX: v24-
  DEPENDENCIES: ${{ github.workspace }}/dependencies-ubuntu.txt
  TZ: UTC
  DEVICE_NAME: unknown
  BUILD_DATE: unknown
  REPO_DATE: unknown
  FW_DATE: unknown
  FW_VER: unknown

jobs:
  check:
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.gh.outputs.tag }}
      date: ${{ steps.gh.outputs.date }}
      sha: ${{ steps.gh.outputs.sha }}
      url: ${{ steps.gh.outputs.url }}
      message: ${{ steps.gh.outputs.message }}
      build_date: ${{ steps.gh.outputs.build_date }}
      fw_date: ${{ steps.gh.outputs.fw_date }}
      fw_ver: ${{ steps.gh.outputs.fw_ver }}
      is_active: ${{ steps.activity.outputs.is_active }}
      test_build: ${{ env.TEST_BUILD }}
      target_name: ${{ env.TARGET_NAME }}
      fake_build: ${{ env.FAKE_BUILD }}
    steps:
      - name: Get repo data via GH API
        id: gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
          BRANCH=$REPO_BRANCH
          REPO_DATE=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.committer.date')
          BUILD_DATE=$( date --utc +'%y%m%d' )
          FW_DATE=$( date --utc +'%Y-%m-%d' )
          TAG=$TAG_PREFIX$BUILD_DATE
          echo "REPO_DATE=$REPO_DATE" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "FW_DATE=$FW_DATE" >> $GITHUB_ENV
          echo "TAG=$TAG" >> $GITHUB_ENV
          wget $REPO_URL/raw/refs/heads/$BRANCH/include/version.mk
          FW_VERSION=$( grep -s '^VERSION_NUMBER:=$(if' version.mk 2>/dev/null )
          [ -z "$FW_VERSION" ] && { echo "ERROR: Cannot find VERSION_NUMBER"; exit 90; }
          FW_VER=$( echo $FW_VERSION | cut -d"," -f3 | cut -d")" -f1 )
          echo 'FW_VER = "'$FW_VER'"'
          echo "FW_VER=$FW_VER" >> $GITHUB_ENV
          rm -f version.mk
          {
            echo "tag=$TAG"
            echo "date=$(date --utc -d $REPO_DATE +%Y%m%d)"
            echo "sha=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.sha[0:7]')"
            echo "url=$(gh api repos/$REPO_LNK/commits/$BRANCH --jq '.html_url')"
            echo "message<<EOF"
            gh api repos/$REPO_LNK/commits/$BRANCH --jq '.commit.message'
            echo EOF
            echo "build_date=$BUILD_DATE"
            echo "fw_date=$FW_DATE"
            echo "fw_ver=$FW_VER"
          } >> $GITHUB_OUTPUT

      - name: Check for repo activity
        id: activity
        env:
          REPO_DATE: ${{ env.REPO_DATE }}
          URL: ${{ steps.gh.outputs.url }}
        run: |
          TIMESTAMP=$(date --utc -d $REPO_DATE +%s)
          DAYS=$(( ( $(date --utc +%s) - $TIMESTAMP ) / 86400 ))
          echo "Repository activity: $(date --utc -d $REPO_DATE)"
          echo "Commit: $URL"
          if [ "${{ github.event_name }}" != "schedule" ]; then
            is_active=true
          elif [[ $DAYS -lt 1 ]] ; then
            is_active=true
          else
            echo "Repository not updated within last 24 hours."
            is_active=false
          fi
          echo "is_active=$is_active" >> $GITHUB_OUTPUT

  build:
    needs: check
    #if: needs.check.outputs.is_active == 'true'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - kng_re
          - r3d
          - r3g
          - r3p
          - rb03
          - rb06
          - rd03
          - rt-ax52
          - rt-ax57m
          - rt-ax59u
          - rt-ax89x
          - tuf_ax4200
          - tuf_ax6000
          - zen-bt8
        isTest:
          - ${{ needs.check.outputs.test_build == 'true' }}
        exclude:
          - { isTest: true }
        include:
          - target: ${{ github.event.inputs.target_name }}
    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -qq update
          #sudo apt-get -qq update && sudo apt-get -qq upgrade
          sudo apt-get -qq install  build-essential gawk flex rsync swig unzip zlib1g-dev file wget
          sudo apt-get -qq install  libc6-dev clang bison g++ gcc-multilib g++-multilib
          sudo apt-get -qq install  gettext git libncurses5-dev libssl-dev python3-setuptools
          sudo apt-get -qq install  libc6-dev pkg-config
          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"

      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
        
      - name: Checkout builder
        uses: actions/checkout@main

      - name: Download OpenWrt sources
        run: |
          git clone --branch $REPO_BRANCH $REPO_URL.git openwrt
          rm -rf .git
          rsync -a openwrt/ ./
          rm -rf openwrt  

      - name: Init builder
        run: |
          chmod +x *.sh
          wget https://github.com/fantastic-packages/packages/raw/refs/heads/24.10/keys/usign/53FF2B6672243D28.pub

      - name: Update OpenWrt packages
        id: update
        env: 
          USE_CACHE: ${{ github.event.inputs.use_cache }}
        run: |
          ./xupdate.sh -f
          mkdir -p logs
          echo "status=success" >> $GITHUB_OUTPUT
          echo "USE_CACHE=$USE_CACHE" >> $GITHUB_ENV
          if [ "$USE_CACHE" = "true" ]; then
              rm -rf staging_dir/
              mkdir -p staging_dir/host
              rm -rf build_dir/
              mkdir -p build_dir/host
          fi

      - name: Restore cache for host tools
        id: tools_cache_restore
        if: github.event.inputs.use_cache == 'true'
        uses: actions/cache/restore@v4
        with:
          key: host-tools-${{ runner.os }}-${{ hashFiles('tools/**') }}
          path: |
            staging_dir/host
            build_dir/host

      - name: Configure
        id: configure
        if: steps.update.outputs.status == 'success'
        env: 
          TARGET: ${{ matrix.target }}
          FW_VER: ${{ needs.check.outputs.fw_ver }}
        run: |
          ./xmake.sh -I -t $TARGET
          G_DEVICE_NAME=$( grep -so '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' )
          [ -z "$G_DEVICE_NAME" ] && exit 31
          G_BOARD_NAME=$( grep -so '^CONFIG_TARGET_BOARD=.*' .config | cut -d'"' -f2 )
          [ -z "$G_BOARD_NAME" ] && exit 32
          G_SUBTARGET_NAME=$( grep -so '^CONFIG_TARGET_SUBTARGET=.*' .config | cut -d'"' -f2 )
          [ -z "$G_SUBTARGET_NAME" ] && exit 33
          G_TARGET_ARCH=$( grep -so '^CONFIG_TARGET_ARCH_PACKAGES=.*' .config | cut -d'"' -f2 )
          echo "G_TARGET_ARCH = $G_TARGET_ARCH"
          VERMAGIC_LIST="vermagic-$G_BOARD_NAME-$G_SUBTARGET_NAME-*.list"
          if [ $(find . -maxdepth 1 -name "$VERMAGIC_LIST" | wc -l) = "0" ]; then
              ./vermagic_update.sh $G_BOARD_NAME $G_SUBTARGET_NAME
          fi
          if [ $(find . -maxdepth 1 -name "$VERMAGIC_LIST" | wc -l) = "0" ]; then
              exit 41
          fi
          FILE_DATE=$(date --utc +'%y%m%d')
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FW_VER=$FW_VER" >> $GITHUB_ENV
          echo "G_DEVICE_NAME=$G_DEVICE_NAME" >> $GITHUB_ENV
          echo "G_BOARD_NAME=$G_BOARD_NAME" >> $GITHUB_ENV
          echo "G_SUBTARGET_NAME=$G_SUBTARGET_NAME" >> $GITHUB_ENV
          echo "G_TARGET_ARCH=$G_TARGET_ARCH" >> $GITHUB_ENV
          echo "FILE_DATE=$FILE_DATE" >> $GITHUB_ENV

      - name: Dump .config file
        run: |
          echo "====== .config ========="
          cat .config
          echo "========================"

      - name: Monitor memory
        run: |
          echo "CPU cores = $(nproc)"
          echo "Memory and swap:"
          sudo free -h
          echo
          sudo swapon --show
          echo
          echo "Available storage:"
          sudo df -h

      - name: Download sources (dl)
        id: download
        if: ${{ steps.configure.outputs.status == 'success' && github.event.inputs.fake_build != 'true' }}
        run: |
          make -j$(nproc) download
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Build tools and toolchain
        id: tools
        if: ${{ steps.configure.outputs.status == 'success' && github.event.inputs.fake_build != 'true' }}
        run: |
          make toolchain/install -j$(nproc)
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Save cache for host tools (use_cache = true)
        id: tools_cache_save
        if: steps.tools.outputs.status == 'success' && github.event.inputs.use_cache == 'true' && steps.tools_cache_restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          key: ${{ steps.tools_cache_restore.outputs.cache-primary-key }}
          path: |
            staging_dir/host
            build_dir/host

      - name: Save cache for host tools (use_cache = false)
        id: tools_cache_save_2
        if: steps.tools.outputs.status == 'success' && github.event.inputs.use_cache != 'true'
        uses: actions/cache/save@v4
        with:
          key: host-tools-${{ runner.os }}-${{ hashFiles('tools/**') }}
          path: |
            staging_dir/host
            build_dir/host

      - name: Kernel compile and install
        id: kernel
        if: ${{ steps.tools.outputs.status == 'success' && github.event.inputs.fake_build != 'true' }}
        run: |
          make target/linux/install -j$(nproc)
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Monitor memory 2
        run: |
          echo "Memory and swap:"
          sudo free -h
          echo
          sudo swapon --show
          echo
          echo "Available storage:"
          sudo df -h

      - name: Build the firmware image
        id: compile
        if: steps.tools.outputs.status == 'success' && steps.kernel.outputs.status == 'success'
        env: 
          TARGET: ${{ matrix.target }}
        run: |
          echo "Run $(nproc) thread compile"
          if [ "$FAKE_BUILD" != "true" -a "$TEST_BUILD" = "true" -a "$PACKAGE_DIR" != "" ]; then
              make $PACKAGE_DIR/compile V=sc BUILD_LOG=1
              exit 99
          fi
          if [ "$FAKE_BUILD" != "true" ]; then
              if [ "$TEST_BUILD" != "true" ]; then
                  make -j$(nproc) world
              else
                  make V=sc world
              fi
          fi
          # process results
          OUT_DIR=bin/targets/$G_BOARD_NAME/$G_SUBTARGET_NAME
          if [ "$FAKE_BUILD" = "true" ]; then
              mkdir -p logs
              mkdir -p $OUT_DIR
              echo "$G_BOARD_NAME $G_SUBTARGET_NAME $G_DEVICE_NAME" > "$OUT_DIR/$G_DEVICE_NAME.txt"
              touch "$OUT_DIR/kernel-debug.tar.zst"
              BLD_VER=$FW_VER
          else
              BLD_VER=$( cat $OUT_DIR/profiles.json | grep -so '"version_number":"[^"]*' | grep -so '[^"]*$' )
          fi
          echo "Firmware $BLD_VER [$FILE_DATE] builded!"
          if [ ! -f $OUT_DIR/kernel-debug.tar.zst ]; then
              echo "File kernel-debug.tar.zst not found!"
              exit 100
          fi
          echo "status=success" >> $GITHUB_OUTPUT
          echo "FW_BUILD_OK=1" >> $GITHUB_ENV
          echo "BLD_VER=$BLD_VER" >> $GITHUB_ENV
          echo "OUT_DIR=$OUT_DIR" >> $GITHUB_ENV

      - name: Mark firmware build failed
        if: false # steps.compile.outcome == 'failure'
        run: |
          echo "Firmware build failed, continuing pipeline"
          echo "FW_BUILD_OK=0" >> $GITHUB_ENV
          OUT_DIR=_bin_fake
          mkdir -p $OUT_DIR
          echo "$G_BOARD_NAME $G_SUBTARGET_NAME $G_DEVICE_NAME" > "$OUT_DIR/$G_DEVICE_NAME.txt"
          touch "$OUT_DIR/kernel-debug.tar.zst"
          echo "BUILD FAILED" > $OUT_DIR/FAILED.txt
          echo "BLD_VER=$FW_VER" >> $GITHUB_ENV
          echo "OUT_DIR=$OUT_DIR" >> $GITHUB_ENV

      - name: Check space usage
        run: df -hT

      - name: Check OOM error
        if: failure()
        run: |
          dmesg | grep -i -E 'oom|killed process' || true
          echo "================== Memory ================="
          free -h
    
      - name: Compress build logs
        if: always()
        env:
          TARGET: ${{ matrix.target }}
          FW_DATE: ${{ needs.check.outputs.fw_date }}
        run: |
          tar -cJvf logs-$TARGET-$FW_DATE.tar.xz logs

      - name: Cleanup OUT directory 
        if: steps.compile.outputs.status == 'success'
        env:
          OUT_DIR: ${{ env.OUT_DIR }}
        run: |
          cd $OUT_DIR
          echo "---------------------------"
          ls -la
          echo "---------------------------"
          rm -rf packages
          rm -f kernel-*
          rm -f *uImage
          rm -f *ubi-cleaner*
          rm -f *-ram-*.bin
          rm -f *-preloader*
          rm -f *-bl31-uboot*
          rm -f *-initramfs-recovery*
          rm -f *-bt8-factory.bin

      - name: Upload OUT directory
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success'
        with:
          name: openwrt-${{ env.BLD_VER }}-${{ needs.check.outputs.build_date }}-${{ env.G_DEVICE_NAME }}
          path: ${{ env.OUT_DIR }}
          if-no-files-found: error

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.target }}-${{ env.FW_DATE }}
          path: logs-*.tar.xz

  release:
    needs: [ check, build ]
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 1
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: openwrt-*

      - name: Check for failed builds
        run: |
          echo "Checking for FAILED.txt in openwrt-* directories..."
          FAILED_DIRS=$( find . -maxdepth 1 -type d -name 'openwrt-*' -exec test -f '{}/FAILED.txt' \; -print )
          if [ -n "$FAILED_DIRS" ]; then
            echo "❌ Build failures detected in:"
            exit 201
          fi
          echo "✅ No FAILED.txt found, proceeding to release"
    
      - name: Put images into zip
        run: |
          mkdir -p public
          find . -mindepth 1 -type d -name 'openwrt-*' -exec sh -c 'zip -0 ./public/$(basename {}).zip -j {} {}/*' \;
          ls -lh ./public/*.zip

      - name: Upload assets
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.check.outputs.tag }}
        with:
          prerelease: ${{ env.TEST_BUILD == 'true' || env.FAKE_BUILD == 'true' }}
          tag_name: ${{ needs.check.outputs.tag }}${{ env.TAG_SUFFIX }}
          name: '${{ needs.check.outputs.tag }}'
          body: |
            OpenWrt ${{ needs.check.outputs.fw_ver }} [${{ needs.check.outputs.fw_date }}]
            author: [remittor](https://github.com/remittor)
          files: ./public/*.zip
