name: build

on:
  workflow_dispatch:
  push:
    tags:
      - v[0-9]+*

env:
  REPO_URL: https://github.com/openwrt-xiaomi/openwrt.git
  REPO_BRANCH: xq-24.10
  BUILD_ROOT: ${{ github.workspace }}/openwrt
  DEPENDENCIES: ${{ github.workspace }}/dependencies-ubuntu.txt
  CUSTOM_FEEDS_SH: ${{ github.workspace }}/custom-feeds.sh
  CUSTOM_PACKAGES_SH: ${{ github.workspace }}/custom-packages.sh
  CUSTOM_CONFIG_SH: ${{ github.workspace }}/custom-config.sh
  TZ: UTC
  DEVICE_NAME: unknown
  FILE_DATE: unknown
  FIRMWARE: unknown  

jobs:
  check:
    runs-on: ubuntu-24.04
    outputs:
      tag: ${{ steps.gh.outputs.tag }}
      date: ${{ steps.gh.outputs.date }}
      sha: ${{ steps.gh.outputs.sha }}
      url: ${{ steps.gh.outputs.url }}
      message: ${{ steps.gh.outputs.message }}
      is_active: ${{ steps.activity.outputs.is_active }}
    steps:
      - name: Get repo data via GH API
        id: gh
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: 'openwrt-xiaomi/openwrt'
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"
          BRANCH=$(gh api repos/$REPO --jq '.default_branch')
          DATE=$(gh api repos/$REPO/commits/$BRANCH --jq '.commit.committer.date')
          {
            echo "tag=$GITHUB_REF_NAME"
            echo "date=$(date --utc -d $DATE +%Y%m%d)"
            echo "sha=$(gh api repos/$REPO/commits/$BRANCH --jq '.sha[0:7]')"
            echo "url=$(gh api repos/$REPO/commits/$BRANCH --jq '.html_url')"
            echo "build_root=$BUILD_ROOT"
            echo "message<<EOF"
            gh api repos/$REPO/commits/$BRANCH --jq '.commit.message'
            echo EOF
          } >> $GITHUB_OUTPUT
          echo "DATE=$DATE" >> $GITHUB_ENV

      - name: Check for repo activity
        id: activity
        env:
          DATE: ${{ env.DATE }}
          URL: ${{ steps.gh.outputs.url }}
        run: |
          TIMESTAMP=$(date --utc -d $DATE +%s)
          DAYS=$(( ( $(date --utc +%s) - $TIMESTAMP ) / 86400 ))
          echo "Repository activity: $(date --utc -d $DATE)"
          echo "Commit: $URL"
          if [ "${{ github.event_name }}" != "schedule" ]; then
            is_active=true
          elif [[ $DAYS -lt 1 ]] ; then
            is_active=true
          else
            echo "Repository not updated within last 24 hours."
            is_active=false
          fi
          echo "is_active=$is_active" >> $GITHUB_OUTPUT

  build:
    needs: check
    #if: needs.check.outputs.is_active == 'true'
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        target:
          - rd03
    steps:
      - name: Initialization environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          #sudo apt-get -qq update && sudo apt-get -qq upgrade
          sudo apt-get -qq update
          sudo apt-get -qq install $(cat $DEPENDENCIES)
          sudo apt-get -qq autoremove --purge
          sudo apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"

      - name: Maximize build disk space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: true
          remove-android: true
          remove-haskell: true
          remove-codeql: true
          remove-docker-images: true
        
      - name: Checkout builder
        uses: actions/checkout@main

      - name: Download OpenWrt sources
        run: git clone --branch $REPO_BRANCH $REPO_URL $BUILD_ROOT

      - name: Init builder
        env:
          BLDROOT: ${{ github.workspace }}
        shell: bash        
        run: |
          rsync -avq --exclude=".*" --exclude="$(basename $BUILD_ROOT)" $BLDROOT/ $BUILD_ROOT/
          cd $BUILD_ROOT
          chmod +x *.sh
          wget https://github.com/fantastic-packages/packages/raw/refs/heads/24.10/keys/usign/53FF2B6672243D28.pub

      - name: Update OpenWrt packages
        run: |
          cd $BUILD_ROOT
          ./xupdate -f

      - name: Build the firmware image
        id: compile
        env: 
          TARGET: ${{ matrix.target }}
        run: |
          cd $BUILD_ROOT
          MAKE_JOBS=$(($(nproc)+1))
          echo "$MAKE_JOBS thread compile"
          ./xmake -m -t $TARGET
          #make -j $MAKE_JOBS download world || make V=sc
          echo "status=success" >> $GITHUB_OUTPUT
          grep '^CONFIG_TARGET.*DEVICE.*=y' .config | sed -r 's/.*DEVICE_(.*)=y/\1/' > DEVICE_NAME
          [ -s DEVICE_NAME ] && echo "DEVICE_NAME=$(cat DEVICE_NAME)" >> $GITHUB_ENV
          grep '^CONFIG_TARGET_BOARD=.*' .config | cut -d'"' -f2 > BOARD_NAME
          [ -s BOARD_NAME ] && echo "BOARD_NAME=$(cat BOARD_NAME)" >> $GITHUB_ENV
          grep '^CONFIG_TARGET_SUBTARGET=.*' .config | cut -d'"' -f2 > SUBTARGET_NAME
          [ -s SUBTARGET_NAME ] && echo "SUBTARGET_NAME=$(cat SUBTARGET_NAME)" >> $GITHUB_ENV
          OUT_DIR=$BUILD_ROOT/bin/$BOARD_NAME/$SUBTARGET_NAME
          echo "OUT_DIR=$OUT_DIR" >> $GITHUB_ENV
          echo "FILE_DATE=$(date +"%y%m%d")" >> $GITHUB_ENV
          echo "FILE_TIME=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          #cat $OUT_DIR/profiles.json | grep -o '"version_number":"[^"]*' | grep -o '[^"]*$' > BLD_VER
          echo "24.10.0-rc5" > BLD_VER
          mkdir -p $OUT_DIR
          echo "$BOARD_NAME $SUBTARGET_NAME $DEVICE_NAME" > "$OUT_DIR/$DEVICE_NAME.txt"
          echo "BLD_VER=$(cat BLD_VER)" >> $GITHUB_ENV

      - name: Check space usage
        run: df -hT

      - name: Compress build logs
        if: always()
        env:
          TARGET: ${{ matrix.target }}
          LOGS_DIR: ${{ env.BUILD_ROOT }}/logs
        run: |
          tar -cJvf logs-$TARGET.tar.xz $LOGS_DIR

      - name: Cleanup OUT directory 
        if: steps.compile.outputs.status == 'success'
        env:
          OUT_DIR: ${{ env.OUT_DIR }}
        run: |
          cd $OUT_DIR
          echo "---------------------------"
          ls -la
          echo "---------------------------"
          rm -rf packages
          rm -f kernel-*
          rm -f *uImage
          rm -f *ubi-cleaner*
          rm -f *-ram-*.bin

      - name: Info
        env:
          OUT_DIR: ${{ env.OUT_DIR }}
        run: |
          echo "---------------------------"
          ls -la
          echo "---------------------------"
          ls -la $BUILD_ROOT
          echo "---------------------------"
          ls -la $OUT_DIR
          echo "---------------------------"

      - name: Upload OUT directory
        uses: actions/upload-artifact@main
        if: steps.compile.outputs.status == 'success'
        with:
          name: openwrt-${{ env.BLD_VER }}-${{ env.FILE_DATE }}-${{ env.DEVICE_NAME }}
          path: ${{ env.OUT_DIR }}
          if-no-files-found: error

      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.target }}
          path: logs-*.tar.xz

  release:
    needs: [ check, build ]
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 1
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: openwrt-*

      - name: Put images into zip
        env:
          TAG: ${{ needs.check.outputs.tag }}
          DATE: ${{ needs.check.outputs.date }}
        run: |
          mkdir -p public
          ls -la
          #find . -name "*-$BRANCH-*.tar" -exec tar -xvf {} --wildcards '*.*pk' \;
          #find $BRANCH -mindepth 1 -type d -exec sh -c 'zip -0 ./public/zapret_${TAG}_$(basename {}).zip -j {} {}/*' \;
          #ls -lh ./public/*.zip

      - name: Upload assets
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG: ${{ needs.check.outputs.tag }}
        with:
          prerelease: false
          tag_name: ${{ needs.check.outputs.tag }}
          name: '${{ needs.check.outputs.tag }} for OpenWrt'
          body: |
            ${{ needs.check.outputs.url }}: ${{ needs.check.outputs.message }}
          files: ./public/*.zip
